[package]
name = "neptune-defi"
description = "Generic tools for decentralized finance on Neptune Cash"
authors = ["Triton Software"]

version = "0.19.0"
edition = "2021"
license = "Apache-2.0"

homepage = "https://neptune.cash/"
repository = "https://github.com/Neptune-Crypto/neptune-core/"

[dependencies]
tasm-lib = "9.0.0"
triton-vm = "9.0.0"
twenty-first = "3.0.0"

neptune-consensus = { version = "0.19.0", path = "../neptune-consensus" }
neptune-primitives = { version = "0.19.0", path = "../neptune-primitives" }

[lints]
workspace = true
