#!/bin/sh
#
# This hook was defined by sword-smith <thor@neptune.cash>
# It's intended to be copied to `.git/hooks/` by `cargo-husky`.

set -e

echo '+cargo clippy --all-targets --all-features -- -D warnings'
cargo clippy --all-targets --all-features -- -D warnings
echo '+cargo fmt --all -- --check'
cargo fmt --all -- --check
echo '+cargo doc --no-deps --workspace'
cargo doc --no-deps --workspace
echo '+cargo test --doc'
cargo test --doc
