name: Cleanup Caches

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cleanup PR Caches
        run: |
          gh cache delete --ref "refs/pull/${{ github.event.pull_request.number }}/merge" --all
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
