on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Build without Cargo.lock

jobs:
  runner-matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      # Run cargo update to ensure this works with latest dependencies, without
      # specific dependencies listed in `Cargo.lock`.
      - name: Update dependencies to latest
        run: cargo update

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          # A unique prefix for the "no-lock" build to avoid
          # conflicting with other caches.
          prefix-key: "v1-no-lock-${{ matrix.os }}"

      - name: Show available compilers (debug)
        if: matrix.os != 'windows-latest'
        run: |
          echo "c++ -> $(which c++ 2>/dev/null || true)"
          c++ --version || true
          echo "clang++ -> $(which clang++ 2>/dev/null || true)"
          clang++ --version || true
        shell: bash

      - name: Install clang (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang
        shell: bash

      - name: Build (linux & macos)
        if: matrix.os != 'windows-latest'
        env:
          CC: clang
          CXX: clang++
        run: cargo check --all --release

      - name: Build (windows)
        if: matrix.os == 'windows-latest'
        run: cargo check --all --release
